In [1]:
import datetime
import csv

# weekNumber = timedelta.
# print('Week number:', weekNumber)
with open('VUAE 2019 - 04&05 - 28 to 05.csv', newline='') as f:
  reader = csv.reader(f)
  for row in reader:
    # do something here with `row`
    break
print(row[0])

PERIODE DU 28/04/19 AU 04/05/19

In [2]:
datetime.date(int(row[0][7:]),int(row[0][3:5]),int(row[0][0:2])).isocalendar()[1]

ValueError: invalid literal for int() with base 10: ' DU 28/04/19 AU 04/05/19'

In [3]:
timedelta

NameError: name 'timedelta' is not defined

In [71]:
import pandas as pd
import numpy as np

In [72]:
rawData = pd.read_csv('RawData.csv', skiprows =1)

In [73]:
rawData

,Sku,401.Quantit,401.Sales Quantity,401.Sales Value,402.Quantit,402.Sales Quantity,402.Sales Value,404.Quantit,404.Sales Quantity,404.Sales Value,...,429.Sales Value,444.Quantit,444.Sales Quantity,444.Sales Value,490.Quantit,490.Sales Quantity,490.Sales Value,TTL Sold Qty,TTL Value,SOH
0,734835,4,0,0,2,0,0,4,0,0,...,0,0,0,0,0,0,0,0,0,40
1,734836,2,0,0,6,1,149,2,1,149,...,0,0,0,0,0,0,0,4,596,35
2,734837,14,2,98,14,0,0,6,2,98,...,0,0,0,0,0,0,0,12,588,205
3,734838,11,0,0,8,0,0,9,0,0,...,0,0,0,0,0,0,0,13,637,142
4,734839,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,734840,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,734841,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,734843,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,734845,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,734848,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,734864,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,25
11,734865,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,49,27
12,734866,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,49,25
13,734867,2,0,0,1,1,219,2,0,0,...,0,0,0,0,0,0,0,2,438,31
14,734868,4,0,0,2,0,0,4,0,0,...,0,0,0,0,0,0,0,1,219,38
15,734869,3,0,0,2,0,0,3,0,0,...,0,0,0,0,0,0,0,1,209,38
16,734870,4,0,0,2,0,0,4,0,0,...,0,0,0,0,0,0,0,0,0,41
17,734871,3,0,0,2,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,39
18,734872,4,0,0,2,0,0,4,0,0,...,0,0,0,0,0,0,0,0,0,41
19,734873,4,0,0,2,0,0,4,0,0,...,0,0,0,0,0,0,0,1,99,37
20,734874,4,0,0,2,0,0,4,0,0,...,0,0,0,0,0,0,0,0,0,41
21,734875,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,734876,3,0,0,2,0,0,3,0,0,...,0,0,0,0,0,0,0,1,119,37
23,734877,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,26
24,734878,4,0,0,2,0,0,4,0,0,...,0,0,0,0,0,0,0,0,0,41
25,734879,3,0,0,2,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,38
26,734880,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,578,24
27,734881,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4,716,35
28,734882,4,0,0,1,1,139,3,0,0,...,0,0,0,0,0,0,0,1,139,35
29,734883,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,734944,2,1,49,2,0,0,3,0,0,...,0,0,0,0,0,0,0,5,245,25
88,734945,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
89,734947,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
90,734948,3,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,25
91,734966,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
92,734968,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93,734970,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94,734971,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
95,734973,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,734975,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,734976,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,734981,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,735669,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,49,22
100,735670,10,0,0,6,0,0,10,0,0,...,0,0,0,0,0,0,0,1,99,110
101,738068,2,0,0,2,0,0,2,0,0,...,0,1,0,0,0,0,0,1,129,26
102,738069,3,0,0,2,0,0,2,0,0,...,0,1,0,0,0,0,0,0,0,26
103,738071,4,0,0,4,0,0,4,0,0,...,0,2,0,0,0,0,0,1,49,48
104,738072,4,0,0,4,0,0,4,0,0,...,0,2,0,0,0,0,0,2,76,46
105,738073,4,0,0,4,0,0,4,0,0,...,0,2,0,0,0,0,0,3,125,46
106,738074,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6
107,738075,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,269,13
108,738076,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,14
109,738077,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,13
110,738078,9,2,98,11,2,98,7,0,0,...,98,6,0,0,0,0,0,32,1568,152
111,738079,3,0,0,2,0,0,2,0,0,...,0,2,0,0,0,0,0,1,99,26
112,738080,3,0,0,2,0,0,2,0,0,...,0,2,0,0,0,0,0,1,60,27
113,738081,2,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,139,12
114,739727,6,0,0,4,0,0,6,0,0,...,0,0,0,0,0,0,0,12,1188,66
115,739728,5,1,99,4,0,0,6,0,0,...,0,0,0,0,0,0,0,5,495,73
116,0,235,7,443,155,6,714,198,4,376,...,98,21,0,0,0,0,0,155,12102,3301

In [76]:
myframe = []
myframe = pd.DataFrame(myframe)

In [4]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd=""
)

mycursor = mydb.cursor()

mycursor.execute("CREATE DATABASE mydatabase")

mydb.close()

In [5]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd=""
)

mycursor = mydb.cursor()

mycursor.execute("SHOW DATABASES")

for x in mycursor:
  print(x)

('information_schema',)
('mydatabase',)
('mysql',)
('performance_schema',)
('phpmyadmin',)
('test',)